version: '3'
services:
  react-app:
    build:
      context: . # which directory to look into
      dockerfile: Dockerfile.dev # path docker file
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules # specifing do not referece node_modules outside container
      - .:/app # specifing to reference current folder in container
  react-test: # second service
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
